<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="basic_laser_pig">

    <!-- Degree-to-radian conversions -->
    <xacro:property name="degrees_30" value="0.523598776"/>
    <xacro:property name="degrees_45" value="0.785398163"/>
    <xacro:property name="degrees_90" value="1.57079633"/>
    <xacro:property name="degrees_180" value="3.14159265"/>

    <!-- vehiclur velocity properties -->
    <xacro:property name="steering_speed" value="1.0472"/> <!-- units of rad/s -->
    <xacro:property name="steering_max_angle" value="1.0"/> <!-- units of rad, needs to be 30 degreees -->
    <xacro:property name="steering_min_angle" value="-1.0"/> <!-- units of rad, needs to be 30 degrees -->
    <xacro:property name="traverse_max_speed" value="4.785"/> <!-- units of m/s 4.785-->

    <!-- Inertia Generator -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- Basic Geometry of Body -->
    <xacro:property name="body_length" value="1.91" />
    <xacro:property name="body_width" value="0.680618" />
    <xacro:property name="body_height" value="1.065022" />
    <xacro:property name="body_mass" value="20.3"/>


    <!-- Front Wheel Properties -->
    <xacro:property name="front_wheel_width" value=".254" />
    <xacro:property name="front_wheel_diameter" value="0.572" />
    <xacro:property name="front_wheel_mass" value="20"/>

    <!-- Steering Link Properties -->
    <xacro:property name="steering_width" value="${front_wheel_width/4}" />
    <xacro:property name="steering_diameter" value="${front_wheel_diameter/5}" />
    <xacro:property name="steering_mass" value="2"/>

    <!-- Rear Wheel Properties -->
    <xacro:property name="rear_wheel_width" value="${front_wheel_width+steering_width}" />
    <xacro:property name="rear_wheel_diameter" value="0.635" />
    <xacro:property name="rear_wheel_mass" value="22.8"/>

    <!-- Camera Properties -->
    <xacro:property name="camera_link" value="0.04"/>

    <!-- Testing Laser link xacro -->
    <xacro:include filename="$(find little_pig_description)/urdf/basic_laser_pig.gazebo" />

    <!-- Dummy Base Link -->
    <link name="base_link" />

    <!-- Actual Base Link -->
    <link name="chassis">
        <visual>
            <origin xyz="${(body_length/2) - 0.1} 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="blue" />
        </visual>
        
        <collision>
            <origin xyz="${(body_length/2) - 0.1} 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        
        <xacro:default_inertial mass="${body_mass}"/>
    </link>
    
    <joint name="base_link_joint" type="fixed">
        <origin xyz="0 0 0.05" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis" />
    </joint>

    <!-- Front Laser -->
    <joint name="front_laser_joint" type="fixed">
      <axis xyz="0 0 0" />
      <origin xyz="${(body_length) + 0.1} 0.0 0.0" rpy="0 0 ${degrees_180}"/> <!-- Was reversed in real world -->
      <parent link="chassis"/>
      <child link="front_laser_link"/>
    </joint>

    <link name="front_laser_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius=".05" length="0.04"/>
        </geometry>
      </collision>
      
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius=".05" length="0.04"/>
        </geometry>
      </visual>
      
      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link>

    <!-- Rear Laser -->
    <joint name="rear_laser_joint" type="fixed">
      <axis xyz="0 0 0" />
      <origin xyz="-0.15 0.0 0.0" rpy="0 0 ${degrees_180}"/> <!-- Was reversed in real world -->
      <parent link="chassis"/>
      <child link="rear_laser_link"/>
    </joint>

    <link name="rear_laser_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius=".05" length="0.04"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius=".05" length="0.04"/>
        </geometry>
      </visual>

      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link>

    <!-- Camera -->
    <joint name="camera_link_joint" type="fixed">
      <axis xyz="0 1 0" />
      <origin xyz="${(body_length) - 0.1} 0.0 ${(body_height/2 + 0.2)}" rpy="0 0 0"/>
      <parent link="chassis"/>
      <child link="camera_link"/>
    </joint>
    
    <link name="camera_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>
        </geometry>
      </collision>
      
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="${camera_link} ${camera_link} ${camera_link}"/>
        </geometry>
        <material name="red"/>
      </visual>
      
      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link> 

    <!-- IMU -->
    <joint name="imu_joint" type="fixed">
        <axis xyz="1 0 0 "/> <!-- 0 1 0 -->
        <origin xyz="0 0 0.19"/>
        <parent link ="chassis"/>
        <child link ="imu_link"/>
    </joint>

    <link name="imu_link">
        <inertial>
            <mass value="0.001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
            <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
            <box size=".001 .001 .001"/>
            </geometry>
        </collision>
	</link>	

    <!-- GPS (THIS JOINT IS UNNECESSARY)
    <joint name="gps_joint" type="fixed">
      <axis xyz="0 0 0 "/>
      <origin xyz="0 0 0.19"/>
      <parent link ="chassis"/>
      <child link ="gps_link"/>
    </joint>

    <link name="gps_link">
        <inertial>
            <mass value="0.001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
        </inertial>

        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
            <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
            <box size=".001 .001 .001"/>
            </geometry>
        </collision>
	</link>	
    -->
												
    <!-- Steering Macro -->
    <xacro:macro name="steering_link" params="prefix reflect">

        <link name="${prefix}_steering_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </collision>

            <xacro:default_inertial mass="${steering_mass}"/>
        </link>

        <joint name="${prefix}_steering_joint" type="revolute">
            <parent link="chassis"/>
            <child link="${prefix}_steering_link"/>
            <axis xyz="0.0 0.0 0.1"/>
            <origin xyz="${(body_length)- 0.2} ${(body_width / 2 + steering_width / 2 + 0.1) * reflect} ${-(body_height/2) + 0.1}" rpy="0.0 0.0 0.0"/>
            <limit lower="${steering_min_angle}" upper="${steering_max_angle}" effort="100000.00" velocity="${steering_speed}"/>
            <!-- effort needs to be very high so we are not constrained by the environment-->
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_steering_link_trans">
            <type>transmission_interface/SimpleTransmission</type>

            <joint name="${prefix}_steering_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>

            <actuator name="${prefix}_steering_link_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Front Wheel Macro -->
    <xacro:macro name="front_wheel_link" params="prefix reflect">

        <link name="${prefix}_front_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
               
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="0.02"/>
                </geometry>

                <surface>
                    <friction>
                        <torsional>
                            <coefficient>2.0</coefficient>
                            <surface_radius>.3025</surface_radius>
                            <use_patch_radius>false</use_patch_radius>
                            <ode>
                                <slip>0.0</slip>
                            </ode>
                        </torsional>
                        
                        <ode>
                            <mu>70000.00</mu>
                            <mu2>70000.00</mu2>
                            <fdir1>1.00000 0.00000 0.00000</fdir1>
                            <slip1>0.00000</slip1>
                            <slip2>0.00000</slip2>
                        </ode>
                    </friction>
                    
                    <contact>
                        <ode>
                            <min_depth>0.4025</min_depth>
                        </ode>
                    </contact>				
                </surface>
            </collision>
            
            <xacro:default_inertial mass="${front_wheel_mass}"/>
        </link>

        <joint name="${prefix}_front_axle" type="continuous">
            <parent link="${prefix}_steering_link"/>
            <child link="${prefix}_front_wheel"/>
            <axis xyz="0.0 0.1 0.0"/>
            <origin xyz="0 ${(front_wheel_width/2 + steering_width/2) * reflect} 0"/>
            <limit effort="100000.00" velocity="${traverse_max_speed * 2 / front_wheel_diameter}"/> <!-- units of rad/s -->
            <!-- effort needs to be very high so we are not constrained by the environment-->
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_front_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            
            <joint name="${prefix}_front_axle">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            
            <actuator name="${prefix}_front_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>


    <!-- Rear Wheel Prismatic Link Macro -->
    <xacro:macro name="rear_wheel_strut_link" params="prefix reflect">

        <link name="${prefix}_rear_wheel_strut">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="0.1" length="0.02"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="0.1" length="0.02"/>
                </geometry>
            </collision>
            
            <xacro:default_inertial mass="${rear_wheel_mass}"/>
        </link>

        <joint name="${prefix}_rear_strut}" type="prismatic">
            <parent link="chassis"/>
            <child link="${prefix}_rear_wheel_strut"/>
            <axis xyz="0.0 0.0 0.1"/>
            <origin xyz="0.0 ${(body_width/2 + 0.1) * reflect} ${-(body_height/2) + 0.1}"/>
            <limit lower="-0.05" upper="0.05" effort="1000.0" velocity="1.0"/>
            <dynamics damping="2.0" friction="8000.0"/>
        </joint>

        <gazebo reference="${prefix}_rear_strut}">
            <implicitSpringDamper>true</implicitSpringDamper>
        </gazebo>
    </xacro:macro>

        

    <!-- Rear Wheel Macro -->
    <xacro:macro name="rear_wheel_link" params="prefix reflect">

        <link name="${prefix}_rear_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="0.01"/>
                </geometry>
            </collision>

            <surface>
                <contact>
                    <ode>
                        <min_depth>0.01</min_depth>
                    </ode>
                </contact>

                <friction>
                    <ode>
                        <mu>1</mu>
                        <mu2>1</mu2>
                        <fdir1>1.0 0 0</fdir1>
                    </ode>
                </friction>
            </surface>

            <xacro:default_inertial mass="${rear_wheel_mass}"/>
        </link>

        <joint name="${prefix}_rear_axle" type="continuous">
            <parent link="${prefix}_rear_wheel_strut"/>
            <child link="${prefix}_rear_wheel"/>
            <axis xyz="0.0 0.1 0.0"/>
            <origin xyz="0.0 ${(rear_wheel_width/2) * reflect} 0.0"/>
            <!-- <limit effort="0.0" velocity="${traverse_max_speed / rear_wheel_diameter}"/> --> <!-- rolling axle -->
            <!-- <limit effort="100000.00" velocity="${traverse_max_speed / rear_wheel_diameter}"/> -->
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_rear_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>

            <joint name="${prefix}_rear_axle">
                <!-- <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface> --> <!-- rolling axle -->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            
            <actuator name="${prefix}_rear_wheel_motor">
                <!-- <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface> --> <!-- rolling axle -->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>





    <!-- Ackermann Steering Macro, this is a dummy joint so it has no visual  -->
    <xacro:macro name="ackermann_steering_link">

        <link name="ackermann_steering_link">
            <!-- <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </visual> -->

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </collision>

            <xacro:default_inertial mass="0.001"/>
        </link>

        <joint name="ackermann_steering_joint" type="revolute">
            <parent link="chassis"/>
            <child link="ackermann_steering_link"/>
            <axis xyz="0.0 0.0 0.1"/>
            <origin xyz="${(body_length)- 0.2} 0.0 1.0" rpy="0.0 0.0 0.0"/>
            <limit lower="${steering_min_angle}" upper="${steering_max_angle}" effort="100000.00" velocity="${steering_speed}"/>
            <!-- effort needs to be very high so we are not constrained by the environment-->
        </joint>

        <!-- The Transmission -->
        <transmission name="ackermann_steering_link_trans">
            <type>transmission_interface/SimpleTransmission</type>

            <joint name="ackermann_steering_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>

            <actuator name="ackermann_steering_link_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>





    <!-- Ackermann Wheel Macro, this is a dummy joint so it has no visual -->
    <xacro:macro name="ackermann_wheel_link">

        <link name="ackermann_rear_wheel">
            <!-- <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
            </visual> -->

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="0.01"/>
                </geometry>
            </collision>

            <xacro:default_inertial mass="0.001"/>
        </link>

        <joint name="ackermann_rear_axle" type="continuous">
            <parent link="chassis"/>
            <child link="ackermann_rear_wheel"/>
            <axis xyz="0.0 0.1 0.0"/>
            <origin xyz="0.0 0.0 1.0" rpy="0.0 0.0 0.0"/>
            <!-- <limit effort="0.0" velocity="${traverse_max_speed / rear_wheel_diameter}"/> --> <!-- rolling axle -->
            <!-- <limit effort="100000.00" velocity="${traverse_max_speed / rear_wheel_diameter}"/> -->
        </joint>

        <!-- The Transmission -->
        <transmission name="ackermann_rear_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>

            <joint name="ackermann_rear_axle">
                <!-- <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface> --> <!-- rolling axle -->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            
            <actuator name="ackermann_rear_wheel_motor">
                <!-- <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface> --> <!-- rolling axle -->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>





    <xacro:steering_link prefix="left" reflect="1" />
    <xacro:steering_link prefix="right" reflect="-1" />

    <xacro:front_wheel_link prefix="left" reflect="1" />
    <xacro:front_wheel_link prefix="right" reflect="-1" />

    <xacro:rear_wheel_strut_link prefix="left" reflect="1"/>
    <xacro:rear_wheel_strut_link prefix="right" reflect="-1"/>

    <xacro:rear_wheel_link prefix="left" reflect="1" />
    <xacro:rear_wheel_link prefix="right" reflect="-1" />

    <xacro:ackermann_steering_link />
    <xacro:ackermann_wheel_link />

    <!-- Gazebo plugin for ROS Control -->
    <gazebo>
        
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotSimType>gazebo_ros_control/AckermannRobotHWSim</robotSimType>
        </plugin>
        
        <plugin name="imu_plugin" filename="libhector_gazebo_ros_imu.so">
            <alwaysOn>true</alwaysOn>
            <bodyName>imu_link</bodyName>
            <topicName>IMU/data</topicName> <!-- Lets solve the namepsace issues -->
            <accelDrift>0.005 0.005 0.005</accelDrift>
            <accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
            <rateDrift>0.005 0.005 0.005</rateDrift>
            <rateGaussianNoise>0.005 0.005 0.005</rateGaussianNoise>
            <headingDrift>0.005 0.005 0.005</headingDrift>
            <gaussianNoise>0.0</gaussianNoise>
            <updateRate>50.0</updateRate>
            <xyzOffsets>0 0 0</xyzOffsets> 
            <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
        
        <plugin name="gps_plugin" filename="libhector_gazebo_ros_gps.so">
            <alwaysOn>1</alwaysOn>
            <updateRate>40.0</updateRate>
            <frameId>base_link</frameId> <!-- Defaults to world? don't put in a "/"-->
            <bodyName>chassis</bodyName>
            <topicName>GPS/fix</topicName>
            <velocityTopicName>GPS/fix_vel</velocityTopicName>
            <drift>0.0001 0.0001 0.0001</drift>
            <referenceLatitude>37.634047</referenceLatitude>
            <referenceLongitude>-97.269368</referenceLongitude>
            <referenceHeading>0</referenceHeading>
            <referenceAltitude>0</referenceAltitude>
        </plugin>
        
    </gazebo>

</robot>
