<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="basic_pig">

    <!-- Degree-to-radian conversions -->
    <xacro:property name="degrees_45" value="0.785398163"/>
    <xacro:property name="degrees_90" value="1.57079633"/>
    <xacro:property name="degrees_180" value="3.14159265"/>

    <!-- Inertia Generator -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- Basic Geometry of Body -->
    <xacro:property name="body_length" value="1.91" />
    <xacro:property name="body_width" value="0.680618" />
    <xacro:property name="body_height" value="1.065022" />
    <xacro:property name="body_mass" value="20.3"/>


    <!-- Front Wheel Properties -->
    <xacro:property name="front_wheel_width" value=".254" />
    <xacro:property name="front_wheel_diameter" value="0.605" />
    <xacro:property name="front_wheel_mass" value="20"/>

    <!-- Steering Link Properties -->
    <xacro:property name="steering_width" value="${front_wheel_width/4}" />
    <xacro:property name="steering_diameter" value="${front_wheel_diameter/5}" />
    <xacro:property name="steering_mass" value="2"/>

    <!-- Rear Wheel Properties -->
    <xacro:property name="rear_wheel_width" value="${front_wheel_width+steering_width}" />
    <xacro:property name="rear_wheel_diameter" value="0.635" />
    <xacro:property name="rear_wheel_mass" value="22.8"/>

    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${body_mass}"/>
    </link>

    <!-- Laser Link -->
    <link name="laser_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius=".05" length="0.04"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius=".05" length="0.04"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="0.01"/>
    </link>

    <joint name="base_link_laser_link" type="fixed">
      <parent link="base_link"/>
      <child link="laser_link"/>
      <axis xyz="0.0 0.0 0.0"/>
      <origin xyz="${(body_length/2) - 0.1} 0.0 ${(body_height/2 + 0.1)}" />
    </joint>

    <gazebo reference="laser_link">
      <sensor type="gpu_ray" name="head_hokuyo_sensor">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>40</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>720</samples>
              <resolution>1</resolution>
              <min_angle>-1.570796</min_angle>
              <max_angle>1.570796</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.10</min>
            <max>30.0</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <!-- Noise parameters based on published spec for Hokuyo laser
                 achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                 stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                 reading. -->
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
          <topicName>/basic_laser_pig/laser/scan</topicName>
          <frameName>laser_link</frameName>
        </plugin>
      </sensor>
    </gazebo>

    <!-- Steering Macro -->
    <xacro:macro name="steering_link" params="prefix reflect">

        <link name="${prefix}_steering_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="${steering_mass}"/>
        </link>

        <joint name="${prefix}_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_steering_link"/>
            <axis xyz="0.0 0.0 0.1"/>
            <origin xyz="${(body_length / 2)- 0.1} ${(body_width / 2 + steering_width / 2) * reflect} ${-(body_height/2) + 0.1}" rpy="0.0 0.0 0.0"/>
            <limit lower="-0.30" upper="0.30" effort="100.00" velocity="100.00"/>
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_steering_link_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_steering_joint">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_steering_link_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Front Wheel Macro -->
    <xacro:macro name="front_wheel_link" params="prefix reflect">

        <link name="${prefix}_front_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="${front_wheel_mass}"/>
        </link>

        <joint name="${prefix}_front_axle" type="continuous">
            <parent link="${prefix}_steering_link"/>
            <child link="${prefix}_front_wheel"/>
            <axis xyz="0.0 0.1 0.0"/>
            <origin xyz="0 ${(front_wheel_width/2 + steering_width/2) * reflect} 0"/>
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_front_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_front_axle">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_front_wheel_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Rear Wheel Macro -->
    <xacro:macro name="rear_wheel_link" params="prefix reflect">

        <link name="${prefix}_rear_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="${rear_wheel_mass}"/>
        </link>

        <joint name="${prefix}_rear_axle" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_rear_wheel"/>
            <axis xyz="0.0 0.1 0.0"/>
            <origin xyz="${-(body_length/2) + 0.1} ${(rear_wheel_width/2 + body_width/2) * reflect} ${-(body_height/2) + 0.1}"/>
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_rear_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_rear_axle">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_rear_wheel_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <xacro:steering_link prefix="left" reflect="1" />
    <xacro:steering_link prefix="right" reflect="-1" />

    <xacro:front_wheel_link prefix="left" reflect="1" />
    <xacro:front_wheel_link prefix="right" reflect="-1" />

    <xacro:rear_wheel_link prefix="left" reflect="1" />
    <xacro:rear_wheel_link prefix="right" reflect="-1" />

    <!-- Gazebo plugin for ROS Control -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/basic_pig</robotNamespace>
        </plugin>
    </gazebo>
</robot>