<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="basic_pig">

    <!-- Degree-to-radian conversions -->
    <xacro:property name="degrees_45" value="0.785398163"/>
    <xacro:property name="degrees_90" value="1.57079633"/>
    <xacro:property name="degrees_180" value="3.14159265"/>

    <!-- vehicular velocity properties -->
    <xacro:property name="steering_speed" value="1.0472"/> <!-- units of rad/s -->
    <xacro:property name="steering_max_angle" value="0.3"/> <!-- units of rad -->
    <xacro:property name="steering_min_angle" value="-0.3"/> <!-- units of rad -->
    <xacro:property name="traverse_max_speed" value="4.785"/> <!-- units of m/s -->

    <!-- Inertia Generator -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- Basic Geometry of Body -->
    <xacro:property name="body_length" value="1.91" />
    <xacro:property name="body_width" value="0.680618" />
    <xacro:property name="body_height" value="1.065022" />
    <xacro:property name="body_mass" value="20.3"/>


    <!-- Front Wheel Properties -->
    <xacro:property name="front_wheel_width" value=".254" />
    <xacro:property name="front_wheel_diameter" value="0.605" />
    <xacro:property name="front_wheel_mass" value="20.0"/>

    <!-- Steering Link Properties -->
    <xacro:property name="steering_width" value="${front_wheel_width/4}" />
    <xacro:property name="steering_diameter" value="${front_wheel_diameter/5}" />
    <xacro:property name="steering_mass" value="2.0"/>

    <!-- Rear Wheel Properties -->
    <xacro:property name="rear_wheel_width" value="${front_wheel_width+steering_width}" />
    <xacro:property name="rear_wheel_diameter" value="0.635" />
    <xacro:property name="rear_wheel_mass" value="22.8"/>

    <!-- Dummy Base Link -->
    <link name="base_link" />

    <!-- Actual Base Link -->
    <link name="chassis">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${body_mass}"/>
    </link>
    <joint name="base_link_joint" type="fixed">
        <origin xyz="0 0 0.05" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis" />
    </joint>

    <!-- Steering Macro -->
    <xacro:macro name="steering_link" params="prefix reflect">

        <link name="${prefix}_steering_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="${steering_mass}"/>
        </link>

        <joint name="${prefix}_steering_joint" type="revolute">
            <parent link="chassis"/>
            <child link="${prefix}_steering_link"/>
            <axis xyz="0.0 0.0 0.1"/>
            <origin xyz="${(body_length / 2)- 0.1} ${(body_width / 2 + steering_width / 2) * reflect} ${-(body_height/2) + 0.1}" rpy="0.0 0.0 0.0"/>
            <limit lower="${steering_min_angle}" upper="${steering_max_angle}" effort="100000.00" velocity="${steering_speed}"/>
            <!-- effort needs to be very high so we are not constrained by the environment-->
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_steering_link_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_steering_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_steering_link_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Front Wheel Macro -->
    <xacro:macro name="front_wheel_link" params="prefix reflect">

        <link name="${prefix}_front_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
		<surface>
			<friction>
				<torsional>
					<coefficient>2.0</coefficient>
					<surface_radius>.3025</surface_radius>
					<use_patch_radius>false</use_patch_radius>
					<ode>
						<slip>0.5</slip>
					</ode>
				</torsional>
				<ode>
					<mu>50000.00</mu>
					<mu2>50000.00</mu2>
					<fdir1>1.00000 0.00000 0.00000</fdir1>
					<slip1>0.00000</slip1>
					<slip2>0.00000</slip2>
				</ode>
			</friction>
			<contact>
				<ode>
					<min_depth>0.3025</min_depth>
				</ode>
			</contact>				
		</surface>
            </collision>
            <xacro:default_inertial mass="${front_wheel_mass}"/>
        </link>

        <joint name="${prefix}_front_axle" type="continuous">
            <parent link="${prefix}_steering_link"/>
            <child link="${prefix}_front_wheel"/>
            <axis xyz="0.0 0.1 0.0"/>
            <origin xyz="0 ${(front_wheel_width/2 + steering_width/2) * reflect} 0"/>
            <limit effort="100000.00" velocity="${traverse_max_speed * 2 / front_wheel_diameter}"/> <!-- units of rad/s -->
            <!-- effort needs to be very high so we are not constrained by the environment-->
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_front_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_front_axle">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_front_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Rear Wheel Macro -->
    <xacro:macro name="rear_wheel_link" params="prefix reflect">

        <link name="${prefix}_rear_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                </geometry>
		<surface>
			<friction>
				<torsional>
					<coefficient>2.0</coefficient>
					<surface_radius>.3175</surface_radius>
					<use_patch_radius>false</use_patch_radius>
					<ode>
						<slip>0.5</slip>
					</ode>
				</torsional>
				<ode>
					<mu>50000.00</mu>
					<mu2>50000.00</mu2>
					<fdir1>1.00000 0.00000 0.00000</fdir1>
					<slip1>0.00000</slip1>
					<slip2>0.00000</slip2>
				</ode>
			</friction>
			<contact>
				<ode>
					<min_depth>0.3175</min_depth>
				</ode>
			</contact>
		</surface>
            </collision>
            <xacro:default_inertial mass="${rear_wheel_mass}"/>
        </link>

        <joint name="${prefix}_rear_axle" type="continuous">
            <parent link="chassis"/>
            <child link="${prefix}_rear_wheel"/>
            <axis xyz="0.0 0.1 0.0"/>
            <origin xyz="${-(body_length/2) + 0.1} ${(rear_wheel_width/2 + body_width/2) * reflect} ${-(body_height/2) + 0.1}"/>
            <limit effort="0.0" velocity="${traverse_max_speed / rear_wheel_diameter}"/> <!-- rolling axle -->
            <!-- <limit effort="100000.00" velocity="${traverse_max_speed / rear_wheel_diameter}"/> -->
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_rear_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_rear_axle">
                <!-- <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface> --> <!-- rolling axle -->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_rear_wheel_motor">
                <!-- <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface> --> <!-- rolling axle -->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <xacro:steering_link prefix="left" reflect="1" />
    <xacro:steering_link prefix="right" reflect="-1" />

    <xacro:front_wheel_link prefix="left" reflect="1" />
    <xacro:front_wheel_link prefix="right" reflect="-1" />

    <xacro:rear_wheel_link prefix="left" reflect="1" />
    <xacro:rear_wheel_link prefix="right" reflect="-1" />

    <!-- Gazebo plugin for ROS Control -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/basic_pig</robotNamespace>
            <robotSimType>gazebo_ros_control/AckermannRobotHWSim</robotSimType> <!-- THIS IS NEW -->
        </plugin>
    </gazebo>
</robot>
