<?xml version="1.0"?>
<robot name="front_wheel" 
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="front_wheel" params="prefix reflect">

        <link name="${prefix}_front_wheel">
            <visual>
                <geometry>
                    <mesh filename="package://little_pig_description/meshes/little_pig_wheel.stl" scale="0.0254 0.0254 0.0254"/>
                </geometry>
                <origin rpy="0.0 0.0 ${degrees_90 * reflect}" xyz="0 0 0.0"/>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90 * reflect} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                    <!-- <mesh filename="package://little_pig_description/meshes/little_pig_wheel.stl" scale="0.0254 0.0254 0.0254"/> -->
                </geometry>
                <surface>
                    <friction>
                        <torsional>
                            <coefficient>2.0</coefficient>
                            <surface_radius>.3025</surface_radius>
                            <use_patch_radius>false</use_patch_radius>
                            <ode>
                                <slip>0.0</slip>
                            </ode>
                        </torsional>
                        
                        <ode>
                            <mu>70000.00</mu>
                            <mu2>70000.00</mu2>
                            <fdir1>1.00000 0.00000 0.00000</fdir1>
                            <slip1>0.00000</slip1>
                            <slip2>0.00000</slip2>
                        </ode>
                    </friction>
                    
                    <contact>
                        <ode>
                            <min_depth>0.4025</min_depth>
                        </ode>
                    </contact>				
                </surface>
            </collision>
            <xacro:default_inertial mass="${front_wheel_mass}"/>
        </link>

        <joint name="${prefix}_front_wheel_joint" type="continuous">
            <parent link="${prefix}_steer_link"/>
            <child link="${prefix}_front_wheel"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <axis xyz="0.0 0.1 0.0"/>
            <!-- <limit effort="1.0" velocity="0.5"/> -->
            <limit effort="30.00" velocity="${traverse_max_speed * 2 / front_wheel_diameter}"/> <!-- units of rad/s -->
        </joint>

        <transmission name="${prefix}_front_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            
            <joint name="${prefix}_front_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            
            <actuator name="${prefix}_front_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

</robot>