<?xml version="1.0"?>
<robot name="rear_wheel" 
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="rear_wheel" params="prefix reflect">

        <link name="${prefix}_rear_wheel">
            <visual>
                <geometry>
                    <mesh filename="package://little_pig_description/meshes/little_pig_wheel.stl" scale="0.0254 0.0254 0.0254"/>
                </geometry>
                <origin rpy="0.0 0.0 ${degrees_90 * reflect}" xyz="0 0 0.0"/>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90 * reflect} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                    <!-- <mesh filename="package://little_pig_description/meshes/little_pig_wheel.stl" scale="0.0254 0.0254 0.0254"/> -->
                </geometry>
            </collision>
            <surface>
                <contact>
                    <ode>
                        <min_depth>0.01</min_depth>
                    </ode>
                </contact>

                <friction>
                    <ode>
                        <mu>1</mu>
                        <mu2>1</mu2>
                        <fdir1>1.0 0 0</fdir1>
                    </ode>
                </friction>
            </surface>
            <xacro:default_inertial mass="${rear_wheel_mass}"/>
        </link>

        <joint name="${prefix}_rear_wheel_joint" type="continuous">
            <parent link="chassis"/>
            <child link="${prefix}_rear_wheel"/>
            <origin xyz="-0.65 ${0.45 * reflect} -0.15" rpy="0.0 0.0 0.0"/>
            <axis xyz="0.0 0.1 0.0"/>
            <!-- <limit effort="1.0" velocity="0.5"/> -->
        </joint>

        <transmission name="${prefix}_rear_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>

            <joint name="${prefix}_rear_wheel_joint">
                <!-- <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface> --> <!-- rolling axle -->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            
            <actuator name="${prefix}_rear_wheel_motor">
                <!-- <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface> --> <!-- rolling axle -->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

</robot>